### ISSUE TITLE
Talismans need variable length

### ISSUE THREAD

**Issue by ahandleman** [diabeatz96/cain#1]
While an Admin can just end the talisman if it hits the required number of slashes, there should be more than 6 possible slashes per talisman.  This is because executions are 6 + CAT slashes in length, so the current limit of 6 slashes per talisman creates a lot of hassle.

**Comment by diabeatz96** [comment]
Noted and working on it.

**Comment by diabeatz96** [comment]
https://github.com/user-attachments/assets/33c4ca86-91e6-452d-9b3b-ebfce0fece96

**Comment by diabeatz96** [comment]
Please update to newest version for changes. Thank you.
