### ISSUE TITLE
Multiple checkbox systems behave unintuitively

### ISSUE THREAD

**Issue by ahandleman** [diabeatz96/cain#16]
Currently if you uncheck a box, it only updates the value if it is greater or equal to the current value.

i.e.

![image](https://github.com/user-attachments/assets/81ef8f5d-2a4d-4b25-9a4e-7d76c4f42b65)
Green will update the value, red will not.
Presumably ideal behavior is to have unchecking a lower level box update the value and update the other boxes accordingly.

**Comment by ahandleman** [comment]
(I can work on this and submit a PR to fix it in 1-2 days)

**Comment by diabeatz96** [comment]
Issue assigned to you. change when needed.

**Comment by diabeatz96** [comment]
So this issue was resolved with last PR correct?

**Comment by ahandleman** [comment]
Completed with #15
