### ISSUE TITLE
Dice Roller box on Exorcist sheet outputs roll card twice

### ISSUE THREAD

**Issue by SpenTrek** [diabeatz96/cain#3]
Fresh install, V12, no modules enabled
![image](https://github.com/user-attachments/assets/a06b35fa-69f0-4d17-8bcc-755014a75895)

**Comment by diabeatz96** [comment]
Thanks for the issue, 

1.) What browser do you use, 
2.) Are you on a track pad? 
3.) Mac, Windows or Linux?

**Comment by diabeatz96** [comment]
issue has been found
