### ISSUE TITLE
Skills all start at 0 instead of 1.

### ISSUE THREAD

**Issue by Zylofan** [diabeatz96/cain#34]
During character creation the game says to start all skills at 1. Up two to 2 and Drop 3 to 0. 

Which means half the skills will be 1. As such, players will have to do less sheet editing if all the skills default to 1 from the start, instead of 0.

(would be nice if they were actual circles you fill in like on the real character sheet, but that is just an aesthetic thing and separate and far less pressing issue)

**Comment by diabeatz96** [comment]
Added in your requested change. New Characters will now drop in with all skills set 1. Furthermore, After our bigger update with
